### ISSUE TITLE
Add mod.conf such that cloning from github directly works

### ISSUE THREAD

**Issue by ghost** [BiLachner/TurtleMiner#10]
I suggest adding a mod.conf, which is a file that... as far as I know, does nothing but let you specify the name of the mod to minetest, otherwise it tries to use the directory name as the mod name. When Minetest attempts to guess the mod name with TurtleMiner, it gives an error because of the capital letters in the directory name. Adding a file called "mod.conf" containing "name = turtleminer" (no quotes of course) would make directly cloning the repo into the minetest mod directory easier. 

See [this example of mod.conf](https://github.com/minetest-mods/moreblocks/blob/master/mod.conf) from another mod.

**Comment by octacian** [comment]
Ah, you are right. I had forgotten about this. Will definitely help, as I've experienced the above annoyance as well. Done, see 27a296b1dae4d8941f9b22d9d4cdf36a974f30a7.

Also, in case you are wondering, there will be a `screenshot.png` soon too.
