### ISSUE TITLE
Improve Remote Control (work remotely, etc...)

### ISSUE THREAD

**Issue by BiLachner** [BiLachner/TurtleMiner#3]
my first remote control does no look very good

**Comment by octacian** [comment]
- [ ] retexture
- [ ] allow to work remotely
- [ ] adjust formspec for remote control

**Comment by octacian** [comment]
Bumped to 0.2 milestone and removed remote controller (temporarily). Other things are currently more important for 0.1 release, like inventory. Full explanation: 0ad3e01367b765be6285af2ace97f5f9a2d68909

**Comment by octacian** [comment]
Done a while ago, forgot to close. See 5951c7dc7d79e9300e9f8e2b346cc660d4bea14f

I've made the remote control actually work remotely, and retextured it to look nicer. (IMO it looks nicer anyways, haven't gotten others opinions yet.)
