### ISSUE TITLE
Make turtles place blocks from the inventory

### ISSUE THREAD

**Issue by BiLachner** [BiLachner/TurtleMiner#4]
- [x] create the buttons in the formspec
- [x] let turtle build a dirt block
- [x] use the blocks from the inventory to build

**Comment by octacian** [comment]
I think this comes along with the visual and text editor. Assigning this enhancement to v0.2 milestone.

**Comment by octacian** [comment]
Inventory complete. A system for tabbed formspecs has also been added.

4d01905c9c95fe8babb77d3ccb8b7a22d623e727
