### ISSUE TITLE
Formspec Icons

### ISSUE THREAD

**Issue by octacian** [BiLachner/TurtleMiner#6]
The formspec is getting better and better, with more and more functionality. However, many of the icons used in the formspec are very high quality, making them look very out of place. The most notable example being the dirt block, which is way to high quality, and quite frankly, looks bad. These textures should all be much lower quality, so that the individual pixels can be seen, much like any other texture in the game.

I feel the same way about the turtle texture, that it is far too high quality. Textures should typically be 16x16 and at most 32x32 for the nicest appearance.

 If you are willing to make the change, I'd be happy to provide textures.

**Comment by BiLachner** [comment]
Yes ... new and better icons are okay ... I'm sorry but at the moment I don't have so much time. School started again and I have some exams that need to be corrected.
For the dirt-block I took a picture from minetest default textures. Just a first version.

**Comment by octacian** [comment]
I've decided not to worry about creating new icons yet. Most importantly is the new editor formspec, as well as settings to change the name of the turtle (and later other settings), the inventory, and the upgrades. Then we'll be able to start work on the visual editor, for which the new icons will be needed. I will therefore close this issue, as it is no longer relevant to current development, and would be assumed for future development without this issue.
